import { FuelType, MaintenanceCategory } from '../types';

export interface CatalogServiceTemplate {
  name: string;
  category: MaintenanceCategory;
  intervalKm: number;
  intervalMonths: number;
  notes?: string;
}

export interface CatalogVehicle {
  id: string;
  brand: string;
  model: string;
  type: 'motor' | 'mobil';
  category: string;
  defaultFuel: FuelType;
  tankCapacityLiters: number;
  popularColors: string[];
  services: CatalogServiceTemplate[];
}

const MATIC_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Matic', category: 'oil', intervalKm: 2500, intervalMonths: 3, notes: 'Ganti rutin tiap 2.000 - 2.500 km' },
  { name: 'Oli Gardan / Transmisi', category: 'transmission', intervalKm: 8000, intervalMonths: 6, notes: 'Ganti setiap 2-3x ganti oli mesin' },
  { name: 'V-Belt & Roller CVT', category: 'general', intervalKm: 24000, intervalMonths: 24, notes: 'Cek & servis CVT tiap 8.000 km, ganti sabuk tiap 24.000 km' },
  { name: 'Filter Udara', category: 'filter', intervalKm: 10000, intervalMonths: 12, notes: 'Ganti baru jika kotor, jangan dicuci air' },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem Depan & Belakang', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Air Radiator Coolant', category: 'general', intervalKm: 12000, intervalMonths: 12, notes: 'Cek level cairan reservoir' },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const BEBEK_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin 4T', category: 'oil', intervalKm: 2500, intervalMonths: 3 },
  { name: 'Set Rantai & Gir Roda', category: 'general', intervalKm: 15000, intervalMonths: 12, notes: 'Lumasi rantai tiap 500-1.000 km' },
  { name: 'Filter Udara', category: 'filter', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const SPORT_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Full Synthetic', category: 'oil', intervalKm: 3000, intervalMonths: 4 },
  { name: 'Filter Oli Mesin', category: 'filter', intervalKm: 6000, intervalMonths: 8, notes: 'Ganti setiap 2x ganti oli mesin' },
  { name: 'Rantai & Gir Sprocket', category: 'general', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Air Radiator Coolant', category: 'general', intervalKm: 12000, intervalMonths: 12 },
  { name: 'Busi Iridium / Standar', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Kampas Rem Cakram', category: 'brakes', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const TRAIL_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin 4T', category: 'oil', intervalKm: 2000, intervalMonths: 3 },
  { name: 'Filter Udara Busa', category: 'filter', intervalKm: 5000, intervalMonths: 6, notes: 'Bersihkan / cuci rutin setelah offroad' },
  { name: 'Rantai & Gear Roda', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem Cakram', category: 'brakes', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const EV_MOTOR_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Kampas Rem Depan & Belakang', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 20000, intervalMonths: 24 },
  { name: 'Drive Belt / Rantai / Hub', category: 'general', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Pemeriksaan Baterai & Kelistrikan', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_GASOLINE_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Full Synthetic & Filter Oli', category: 'oil', intervalKm: 10000, intervalMonths: 6, notes: 'Ganti oli dan filter oli setiap 10.000 km' },
  { name: 'Filter Udara Mesin', category: 'filter', intervalKm: 20000, intervalMonths: 12 },
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Oli Transmisi Matic (ATF/CVT)', category: 'transmission', intervalKm: 40000, intervalMonths: 24, notes: 'Kuras atau ganti oli transmisi matic' },
  { name: 'Minyak Rem & Minyak Kopling', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Busi (Spark Plug)', category: 'general', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Kampas Rem (Brake Pads)', category: 'brakes', intervalKm: 30000, intervalMonths: 24 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_DIESEL_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Diesel & Filter Oli', category: 'oil', intervalKm: 10000, intervalMonths: 6, notes: 'Ganti oli diesel dan filter oli' },
  { name: 'Filter Solar / Fuel Filter', category: 'filter', intervalKm: 15000, intervalMonths: 12, notes: 'Kuras sedimenter dan ganti filter solar' },
  { name: 'Filter Udara Mesin', category: 'filter', intervalKm: 20000, intervalMonths: 12 },
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Oli Gardan & Transmisi', category: 'transmission', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_EV_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Coolant Pendingin Baterai & Inverter', category: 'general', intervalKm: 60000, intervalMonths: 36 },
  { name: 'Kampas Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 36 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

export const VEHICLE_CATALOG: CatalogVehicle[] = [
  // ==================== SEPEDA MOTOR ====================
  // HONDA MATIC
  {
    id: 'honda-beat-2024-2026',
    brand: 'Honda',
    model: 'BeAT 110 (Deluxe / Street 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Biru Matte', 'Silver', 'Cokelat'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-scoopy-2024-2026',
    brand: 'Honda',
    model: 'Scoopy 110 (Prestige / Stylish 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Putih Prestige', 'Hitam Prestige', 'Hijau Stylish', 'Merah Stylish'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-vario-125-2024-2026',
    brand: 'Honda',
    model: 'Vario 125 (CBS / ISS 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Biru Matte', 'Merah Metalik'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-vario-160',
    brand: 'Honda',
    model: 'Vario 160 (CBS / ABS)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['Hitam Doff', 'Putih Grande', 'Merah Doff', 'Biru Matte'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-pcx-160-2024-2026',
    brand: 'Honda',
    model: 'PCX 160 (CBS / ABS 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Hitam Glossy', 'Putih Mutiara', 'Biru Navy Matte', 'Merah Doff'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-adv-160',
    brand: 'Honda',
    model: 'ADV 160 (CBS / ABS Adventure)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Hitam Doff', 'Merah Doff', 'Putih Mutiara', 'Abu-abu Matte'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-stylo-160-2024-2026',
    brand: 'Honda',
    model: 'Stylo 160 (CBS / ABS Retro Modern)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.0,
    popularColors: ['Royal Matte Black', 'Royal Matte White', 'Glam Red', 'Glam Beige'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-genio',
    brand: 'Honda',
    model: 'Genio 110',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam', 'Putih', 'Cokelat', 'Biru'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-forza-250',
    brand: 'Honda',
    model: 'Forza 250 Maxi Scooter',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 11.7,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Abu-abu'],
    services: MATIC_SERVICES,
  },

  // YAMAHA MATIC
  {
    id: 'yamaha-nmax-turbo-2024-2026',
    brand: 'Yamaha',
    model: 'NMAX Turbo / Tech MAX (YECVT 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.1,
    popularColors: ['Magma Black', 'Elixir Dark Silver', 'Ceramic White', 'Dull Blue'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-nmax-155-connected',
    brand: 'Yamaha',
    model: 'NMAX 155 Connected / Standard',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.1,
    popularColors: ['Matte Black', 'Prestige Silver', 'Matte Blue', 'Metallic Red'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-aerox-155-alpha-2024-2026',
    brand: 'Yamaha',
    model: 'Aerox 155 Connected / CyberCity / SP',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['CyberCity Orange', 'Matte Black Gold', 'Silver Cyan', 'Racing Blue'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-fazzio-hybrid',
    brand: 'Yamaha',
    model: 'Fazzio Hybrid-Connected 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.1,
    popularColors: ['Neo Cyan', 'Neo Red', 'Lux White Pearl', 'Lux Prestige Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-grand-filano-hybrid',
    brand: 'Yamaha',
    model: 'Grand Filano Hybrid-Connected 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.4,
    popularColors: ['Lux White Pearl', 'Lux Dark Blue', 'Neo Dull Blue', 'Neo Pink Mauve'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-lexi-lx-155-2024-2026',
    brand: 'Yamaha',
    model: 'Lexi LX 155 (Standard / S / Connected-ABS)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Magma Black', 'Elixir Dark Silver', 'Matte Red', 'Metallic Black'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-xmax-connected-250',
    brand: 'Yamaha',
    model: 'XMAX Connected 250',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 13.0,
    popularColors: ['Dark Petrol', 'Premium Black', 'Prestige Grey'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-xride-125',
    brand: 'Yamaha',
    model: 'X-Ride 125 Crossover',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Sand Matte', 'Hitam Merah', 'Cyan Yellow', 'Putih'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-mio-m3',
    brand: 'Yamaha',
    model: 'Mio M3 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Cyan', 'Putih Kuning', 'Merah Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-gear-125',
    brand: 'Yamaha',
    model: 'Gear 125 Multiguna',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Navy', 'Matte Blue', 'Merah Grey', 'Cyan'],
    services: MATIC_SERVICES,
  },

  // SUZUKI MATIC
  {
    id: 'suzuki-burgman-street-125ex',
    brand: 'Suzuki',
    model: 'Burgman Street 125 EX',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.5,
    popularColors: ['Metallic Matte Black', 'Metallic Matte Platinum Silver', 'Metallic Royal Bronze'],
    services: MATIC_SERVICES,
  },
  {
    id: 'suzuki-avenis-125',
    brand: 'Suzuki',
    model: 'Avenis 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.2,
    popularColors: ['Pearl Mirage White', 'Metallic Matte Fibroin Grey'],
    services: MATIC_SERVICES,
  },
  {
    id: 'suzuki-nex-ii',
    brand: 'Suzuki',
    model: 'Nex II / Crossover 115',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.6,
    popularColors: ['Solid Black', 'Titan Black', 'Bordeaux Red'],
    services: MATIC_SERVICES,
  },

  // VESPA & PIAGGIO MATIC
  {
    id: 'vespa-sprint-150-i-get',
    brand: 'Vespa',
    model: 'Sprint 150 i-get ABS / Sprint S',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 7.0,
    popularColors: ['Green Tenace', 'Yellow Sole', 'White Innocenza', 'Black Vulcano'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-primavera-150-i-get',
    brand: 'Vespa',
    model: 'Primavera 150 i-get ABS / Primavera S',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 7.0,
    popularColors: ['Blue Capri', 'Beige Sabbia', 'Green Relax', 'White Innocenza'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-gts-super-150-300',
    brand: 'Vespa',
    model: 'GTS Super Sport 150 / 300 HPE',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 8.5,
    popularColors: ['Orange Tramonto', 'White Innocenza', 'Black Vulcano', 'Green Olive'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-lx-125-i-get',
    brand: 'Vespa',
    model: 'LX 125 i-get',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.0,
    popularColors: ['Red Passione', 'Grey Delicato', 'White Innocenza'],
    services: MATIC_SERVICES,
  },

  // BEBEK / UNDERBONE
  {
    id: 'honda-supra-x-125',
    brand: 'Honda',
    model: 'Supra X 125 FI (Helm-in / CW)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hitam Merah', 'Hitam Doff', 'Hitam Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-revo-x',
    brand: 'Honda',
    model: 'Revo X 110 FI',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Attractive Red', 'Quantum Black', 'Galaxy Blue'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-gtr-150',
    brand: 'Honda',
    model: 'Supra GTR 150 Sport Underbone',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.5,
    popularColors: ['Spartan Red', 'Gun Black', 'Exclusive Matte Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-super-cub-c125',
    brand: 'Honda',
    model: 'Super Cub C125 Classic',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 3.7,
    popularColors: ['Pearl Cadet Gray', 'Pearl Nebula Red', 'Matte Axis Gray'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-mx-king-150',
    brand: 'Yamaha',
    model: 'MX King 150',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Cyan Silver', 'Racing Blue', 'Red Black'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-jupiter-z1',
    brand: 'Yamaha',
    model: 'Jupiter Z1 115 FI',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.1,
    popularColors: ['Metallic Blue', 'Metallic Red', 'Metallic Black'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-satria-f150',
    brand: 'Suzuki',
    model: 'Satria F150 FI Hyper Underbone',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.0,
    popularColors: ['Titan Black', 'Pearl Bright Ivory', 'Solarize Silver'],
    services: BEBEK_SERVICES,
  },

  // SPORT & NAKED
  {
    id: 'honda-cbr150r',
    brand: 'Honda',
    model: 'CBR150R (Non-ABS / ABS)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Racing Red', 'Matte Black', 'Tricolor', 'MotoGP Edition'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-cbr250rr',
    brand: 'Honda',
    model: 'CBR250RR SP Quick Shifter',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.5,
    popularColors: ['Bravery Red Black', 'Mystic Blue', 'Honda Tricolor', 'Black Freedom'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-cb150r-streetfire',
    brand: 'Honda',
    model: 'CB150R Streetfire Naked',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Macho Matte Black', 'Fury Matte Red', 'Armored Matte Gray'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-r15-connected',
    brand: 'Yamaha',
    model: 'YZF-R15 V4 / R15M Connected-ABS',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 11.0,
    popularColors: ['Icon Blue', 'Tech Black', 'Silver M-Sport', 'World GP 60th'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-r25',
    brand: 'Yamaha',
    model: 'YZF-R25 Twin Cylinder',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.0,
    popularColors: ['Racing Blue', 'Metallic Black'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-xsr-155',
    brand: 'Yamaha',
    model: 'XSR 155 Heritage Sport',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 10.4,
    popularColors: ['Matte Black Elegance', 'Metallic Red Authentic', 'Light Blue Wanderlust'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-mt-15',
    brand: 'Yamaha',
    model: 'MT-15 Master of Torque',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 10.4,
    popularColors: ['Metallic Dark Grey (Cyan)', 'Metallic Blue', 'Matte Dark Grey'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-ninja-zx25r',
    brand: 'Kawasaki',
    model: 'Ninja ZX-25R / ZX-25RR (4 Silinder)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 15.0,
    popularColors: ['Lime Green / Ebony', 'Metallic Matte Graphenesteel Gray', 'Candy Persimmon Red'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-ninja-250',
    brand: 'Kawasaki',
    model: 'Ninja 250 FI (Twin Cylinder)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.0,
    popularColors: ['Lime Green', 'Metallic Carbon Gray', 'Passion Red'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-w175',
    brand: 'Kawasaki',
    model: 'W175 SE / Cafe / TR Retro',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 14.0,
    popularColors: ['Ebony Black', 'Metallic Ocean Blue', 'White'],
    services: SPORT_SERVICES,
  },
  {
    id: 'ktm-duke-250-390',
    brand: 'KTM',
    model: 'Duke 250 / 390 Naked',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 13.4,
    popularColors: ['Electronic Orange', 'Atlantic Blue', 'Silver Metallic'],
    services: SPORT_SERVICES,
  },

  // TRAIL / DUAL PURPOSE
  {
    id: 'honda-crf150l',
    brand: 'Honda',
    model: 'CRF150L Dual Purpose',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.2,
    popularColors: ['Extreme Red', 'Extreme Black', 'Extreme White', 'Extreme Green'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'yamaha-wr155r',
    brand: 'Yamaha',
    model: 'WR 155 R VVA',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Yamaha Blue', 'Yamaha Black', 'Monster Energy'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'kawasaki-klx-150',
    brand: 'Kawasaki',
    model: 'KLX 150 S / SE / SM (Supermoto)',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 6.9,
    popularColors: ['Lime Green', 'Ebony', 'Neon Green', 'Vivid Orange'],
    services: TRAIL_SERVICES,
  },

  // MOTOR LISTRIK (EV)
  {
    id: 'polytron-fox-r',
    brand: 'Polytron',
    model: 'Fox-R (3.74 kWh)',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Crimson Red', 'Cherry Red', 'Bumblebee Yellow', 'Midnight Black', 'White Pearl'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'alva-cervo',
    brand: 'Alva',
    model: 'Alva Cervo Boost / Cervo Q',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Mars Cooper', 'Supernova Black', 'Nebula Green', 'Halo White'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'honda-em1-e',
    brand: 'Honda',
    model: 'EM1 e: / EM1 e: PLUS',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Innovative White', 'Intelligent Matte Black', 'Smart Red'],
    services: EV_MOTOR_SERVICES,
  },

  // ==================== MOBIL ====================
  // TOYOTA
  {
    id: 'toyota-avanza-2024-2026',
    brand: 'Toyota',
    model: 'Avanza 1.3 / 1.5 G CVT (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Putih Mutiara', 'Hitam Metalik', 'Silver Mika', 'Abu-abu Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-veloz-2024-2026',
    brand: 'Toyota',
    model: 'Veloz 1.5 Q CVT TSS (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 43,
    popularColors: ['Platinum White Pearl', 'Black Metallic', 'Silver Mica Metallic', 'Dark Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-innova-zenix-gasoline',
    brand: 'Toyota',
    model: 'Kijang Innova Zenix 2.0 V / G Bensin',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 52,
    popularColors: ['Platinum White Pearl', 'Attitude Black', 'Silver Metallic', 'Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-innova-zenix-hybrid',
    brand: 'Toyota',
    model: 'Kijang Innova Zenix Hybrid 2.0 Q Modellista',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 52,
    popularColors: ['Platinum White Pearl', 'Attitude Black', 'Dark Steel', 'Silver Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-fortuner-gr-sport-diesel',
    brand: 'Toyota',
    model: 'Fortuner 2.8 VRZ / GR Sport Diesel 4x2',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 80,
    popularColors: ['Super White', 'Attitude Black', 'Silver Metallic', 'Dark Gray'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'toyota-raize-turbo',
    brand: 'Toyota',
    model: 'Raize 1.0 Turbo GR Sport CVT TSS',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 36,
    popularColors: ['Turquoise MM Black (Two Tone)', 'White Black', 'Yellow Black', 'Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-rush-gr-sport',
    brand: 'Toyota',
    model: 'Rush 1.5 S GR Sport',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['White', 'Black Mica', 'Silver Mica', 'Bronze Mica Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-calya',
    brand: 'Toyota',
    model: 'Calya 1.2 G',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['Putih', 'Hitam', 'Silver', 'Abu-abu Metalik', 'Merah'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-agya-gr-sport',
    brand: 'Toyota',
    model: 'Agya 1.2 G / GR Sport',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['White', 'Black', 'Red', 'Yellow', 'Silver'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-yaris-cross-hybrid',
    brand: 'Toyota',
    model: 'Yaris Cross 1.5 S Hybrid GR Sport TSS',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 36,
    popularColors: ['Platinum White Pearl Black', 'Scarlet Black', 'Dark Red Black', 'Silver Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HONDA MOBIL
  {
    id: 'honda-brio-satya-rs-2024-2026',
    brand: 'Honda',
    model: 'Brio Satya E / RS CVT (2024-2026)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 35,
    popularColors: ['Electric Lime Metallic', 'Crystal Black Pearl', 'Taffeta White', 'Rallye Red', 'Phoenix Orange Pearl Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-hrv-se-turbo',
    brand: 'Honda',
    model: 'HR-V 1.5 SE / RS Turbo',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Sand Khaki Pearl Two Tone', 'Ignite Red Metallic Two Tone', 'Platinum White Pearl', 'Meteoroid Gray'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-crv-turbo-ehev-2024-2026',
    brand: 'Honda',
    model: 'CR-V 1.5 Turbo / 2.0 RS e:HEV Hybrid (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 53,
    popularColors: ['Canyon River Blue Metallic', 'Platinum White Pearl', 'Crystal Black Pearl', 'Ignite Red Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-brv-n7x-edition',
    brand: 'Honda',
    model: 'BR-V Prestige with Honda SENSING / N7X Edition',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Sand Khaki Pearl', 'Premium Opal White Pearl', 'Crystal Black Pearl', 'Meteoroid Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-wrv-rs',
    brand: 'Honda',
    model: 'WR-V 1.5 RS with Honda SENSING',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 35,
    popularColors: ['Ignite Red Metallic Two Tone', 'Stellar Diamond Pearl', 'Meteoroid Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-city-hatchback-rs',
    brand: 'Honda',
    model: 'City Hatchback RS CVT Honda SENSING',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Phoenix Orange Pearl', 'Platinum White Pearl', 'Rallye Red', 'Meteoroid Gray'],
    services: CAR_GASOLINE_SERVICES,
  },

  // MITSUBISHI
  {
    id: 'mitsubishi-xpander-cross-2024-2026',
    brand: 'Mitsubishi',
    model: 'Xpander Ultimate / Xpander Cross CVT (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 45,
    popularColors: ['Quartz White Pearl', 'Blade Silver Metallic', 'Jet Black Mica', 'Green Bronze Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mitsubishi-pajero-sport-dakar-2024-2026',
    brand: 'Mitsubishi',
    model: 'Pajero Sport Dakar Ultimate 4x2 / 4x4 (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 68,
    popularColors: ['White Diamond', 'Black Mica', 'Blade Silver Metallic', 'Deep Bronze'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'mitsubishi-xforce',
    brand: 'Mitsubishi',
    model: 'Xforce Ultimate / Exceed CVT (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Energetic Yellow Metallic', 'Quartz White Pearl', 'Jet Black Mica', 'Red Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },

  // SUZUKI MOBIL
  {
    id: 'suzuki-xl7-hybrid',
    brand: 'Suzuki',
    model: 'XL7 Smart Hybrid Alpha / Beta',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Savanna Ivory Black Two Tone', 'Rising Orange Black', 'White Pearl', 'Metallic Magma Gray'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-ertiga-hybrid',
    brand: 'Suzuki',
    model: 'All New Ertiga Cruise / Hybrid GX',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Cool Black', 'Pearl Snow White', 'Metallic Magma Gray', 'Prime Cool Black Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-jimny-3-5-door',
    brand: 'Suzuki',
    model: 'Jimny 3-Door / 5-Door 4x4 (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Kinetic Yellow Black', 'Jungle Green', 'Chiffon Ivory', 'Granite Gray'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HYUNDAI
  {
    id: 'hyundai-stargazer-x',
    brand: 'Hyundai',
    model: 'Stargazer X Prime / Trend',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 40,
    popularColors: ['Optic White Matte', 'Titan Gray Matte', 'Creamy White Pearl', 'Midnight Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'hyundai-creta-prime',
    brand: 'Hyundai',
    model: 'Creta Prime / Alpha 1.5 IVT',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Magnetic Silver Matte', 'Dragon Red Pearl', 'Galaxy Blue Pearl', 'Midnight Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'hyundai-ioniq-5-ev',
    brand: 'Hyundai',
    model: 'Ioniq 5 Signature Long Range EV',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Gravity Gold Matte', 'Optic White', 'Midnight Black Pearl', 'Titan Gray Metallic'],
    services: CAR_EV_SERVICES,
  },

  // WULING
  {
    id: 'wuling-air-ev-long-range',
    brand: 'Wuling',
    model: 'Air EV Long Range / Standard Range',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Pristine White', 'Avocado Green', 'Lemon Yellow', 'Peach Pink', 'Galaxy Blue'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-binguo-ev',
    brand: 'Wuling',
    model: 'Binguo EV Premium / Long Range (333 - 410 KM)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Milk Tea', 'Mousse Green', 'Galaxy Blue'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-cloud-ev-2024-2026',
    brand: 'Wuling',
    model: 'Cloud EV 460 KM (2024-2026)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Milk Tea', 'Breeze White', 'Starry Black'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-alvez',
    brand: 'Wuling',
    model: 'Alvez EX / CE 1.5 CVT',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Tungsten Steel Gray', 'Pristine White', 'Starry Black', 'Aurora Silver', 'Carnelian Red'],
    services: CAR_GASOLINE_SERVICES,
  },

  // BYD
  {
    id: 'byd-m6-mpv-ev-2024-2026',
    brand: 'BYD',
    model: 'M6 Superior / Extended MPV EV (2024-2026)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Crystal White', 'Harbour Grey', 'Quartz Blue', 'Cosmos Black'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'byd-seal-performance-ev',
    brand: 'BYD',
    model: 'Seal Performance AWD / Premium EV',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Arctic Blue', 'Aurora White', 'Atlantis Grey', 'Cosmos Black'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'byd-atto-3-ev',
    brand: 'BYD',
    model: 'Atto 3 Superior Extended EV',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Ski White', 'Boulder Grey', 'Surf Blue', 'Forest Green', 'Cosmos Black'],
    services: CAR_EV_SERVICES,
  },
];

export const POPULAR_MOTOR_BRANDS = ['Semua', 'Honda', 'Yamaha', 'Suzuki', 'Kawasaki', 'Vespa', 'KTM', 'Polytron', 'Alva'];
export const POPULAR_CAR_BRANDS = ['Semua', 'Toyota', 'Honda', 'Mitsubishi', 'Suzuki', 'Daihatsu', 'Hyundai', 'Wuling', 'BYD'];
export const MOTOR_CATEGORIES = ['Semua', 'Matic', 'Bebek', 'Sport', 'Trail', 'Listrik'];
export const CAR_CATEGORIES = ['Semua', 'MPV', 'SUV', 'Hatchback', 'Listrik'];
