import { FuelType, MaintenanceCategory } from '../types';

export interface CatalogServiceTemplate {
  name: string;
  category: MaintenanceCategory;
  intervalKm: number;
  intervalMonths: number;
  notes?: string;
}

export interface CatalogVehicle {
  id: string;
  brand: string;
  model: string;
  type: 'motor' | 'mobil';
  category: string;
  defaultFuel: FuelType;
  tankCapacityLiters: number;
  popularColors: string[];
  services: CatalogServiceTemplate[];
}

const MATIC_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Matic', category: 'oil', intervalKm: 2500, intervalMonths: 3, notes: 'Ganti rutin tiap 2.000 - 2.500 km' },
  { name: 'Oli Gardan / Transmisi', category: 'transmission', intervalKm: 8000, intervalMonths: 6, notes: 'Ganti setiap 2-3x ganti oli mesin' },
  { name: 'V-Belt & Roller CVT', category: 'general', intervalKm: 24000, intervalMonths: 24, notes: 'Cek & servis CVT tiap 8.000 km, ganti sabuk tiap 24.000 km' },
  { name: 'Filter Udara', category: 'filter', intervalKm: 10000, intervalMonths: 12, notes: 'Ganti baru jika kotor, jangan dicuci air' },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem Depan & Belakang', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Air Radiator Coolant', category: 'general', intervalKm: 12000, intervalMonths: 12, notes: 'Cek level cairan reservoir' },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const BEBEK_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin 4T', category: 'oil', intervalKm: 2500, intervalMonths: 3 },
  { name: 'Set Rantai & Gir Roda', category: 'general', intervalKm: 15000, intervalMonths: 12, notes: 'Lumasi rantai tiap 500-1.000 km' },
  { name: 'Filter Udara', category: 'filter', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const SPORT_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Full Synthetic', category: 'oil', intervalKm: 3000, intervalMonths: 4 },
  { name: 'Filter Oli Mesin', category: 'filter', intervalKm: 6000, intervalMonths: 8, notes: 'Ganti setiap 2x ganti oli mesin' },
  { name: 'Rantai & Gir Sprocket', category: 'general', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Air Radiator Coolant', category: 'general', intervalKm: 12000, intervalMonths: 12 },
  { name: 'Busi Iridium / Standar', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Kampas Rem Cakram', category: 'brakes', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const TRAIL_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin 4T', category: 'oil', intervalKm: 2000, intervalMonths: 3 },
  { name: 'Filter Udara Busa', category: 'filter', intervalKm: 5000, intervalMonths: 6, notes: 'Bersihkan / cuci rutin setelah offroad' },
  { name: 'Rantai & Gear Roda', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Busi', category: 'general', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Kampas Rem Cakram', category: 'brakes', intervalKm: 8000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const EV_MOTOR_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Kampas Rem Depan & Belakang', category: 'brakes', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 20000, intervalMonths: 24 },
  { name: 'Drive Belt / Rantai / Hub', category: 'general', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Pemeriksaan Baterai & Kelistrikan', category: 'general', intervalKm: 10000, intervalMonths: 12 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_GASOLINE_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Full Synthetic & Filter Oli', category: 'oil', intervalKm: 10000, intervalMonths: 6, notes: 'Ganti oli dan filter oli setiap 10.000 km' },
  { name: 'Filter Udara Mesin', category: 'filter', intervalKm: 20000, intervalMonths: 12 },
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Oli Transmisi Matic (ATF/CVT)', category: 'transmission', intervalKm: 40000, intervalMonths: 24, notes: 'Kuras atau ganti oli transmisi matic' },
  { name: 'Minyak Rem & Minyak Kopling', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Busi (Spark Plug)', category: 'general', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Kampas Rem (Brake Pads)', category: 'brakes', intervalKm: 30000, intervalMonths: 24 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_DIESEL_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Oli Mesin Diesel & Filter Oli', category: 'oil', intervalKm: 10000, intervalMonths: 6, notes: 'Ganti oli diesel dan filter oli' },
  { name: 'Filter Solar / Fuel Filter', category: 'filter', intervalKm: 15000, intervalMonths: 12, notes: 'Kuras sedimenter dan ganti filter solar' },
  { name: 'Filter Udara Mesin', category: 'filter', intervalKm: 20000, intervalMonths: 12 },
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Oli Gardan & Transmisi', category: 'transmission', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

const CAR_EV_SERVICES: CatalogServiceTemplate[] = [
  { name: 'Filter Kabin AC', category: 'filter', intervalKm: 15000, intervalMonths: 12 },
  { name: 'Minyak Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 24 },
  { name: 'Rotasi, Spooring & Balancing Ban', category: 'general', intervalKm: 10000, intervalMonths: 6 },
  { name: 'Coolant Pendingin Baterai & Inverter', category: 'general', intervalKm: 60000, intervalMonths: 36 },
  { name: 'Kampas Rem', category: 'brakes', intervalKm: 40000, intervalMonths: 36 },
  { name: 'Pajak STNK Tahunan', category: 'tax', intervalKm: 0, intervalMonths: 12 },
];

export const VEHICLE_CATALOG: CatalogVehicle[] = [
  // ==================== SEPEDA MOTOR ====================
  // HONDA MATIC
  {
    id: 'honda-beat-2024-2026',
    brand: 'Honda',
    model: 'BeAT 110 (Deluxe / Street 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Biru Matte', 'Silver', 'Cokelat'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-scoopy-2024-2026',
    brand: 'Honda',
    model: 'Scoopy 110 (Prestige / Stylish 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Putih Prestige', 'Hitam Prestige', 'Hijau Stylish', 'Merah Stylish'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-vario-125-2024-2026',
    brand: 'Honda',
    model: 'Vario 125 (CBS / ISS 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Biru Matte', 'Merah Metalik'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-vario-160',
    brand: 'Honda',
    model: 'Vario 160 (CBS / ABS)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['Hitam Doff', 'Putih Grande', 'Merah Doff', 'Biru Matte'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-pcx-160-2024-2026',
    brand: 'Honda',
    model: 'PCX 160 (CBS / ABS 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Hitam Glossy', 'Putih Mutiara', 'Biru Navy Matte', 'Merah Doff'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-adv-160',
    brand: 'Honda',
    model: 'ADV 160 (CBS / ABS Adventure)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Hitam Doff', 'Merah Doff', 'Putih Mutiara', 'Abu-abu Matte'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-stylo-160-2024-2026',
    brand: 'Honda',
    model: 'Stylo 160 (CBS / ABS Retro Modern)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.0,
    popularColors: ['Royal Matte Black', 'Royal Matte White', 'Glam Red', 'Glam Beige'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-genio',
    brand: 'Honda',
    model: 'Genio 110',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam', 'Putih', 'Cokelat', 'Biru'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-forza-250',
    brand: 'Honda',
    model: 'Forza 250 Maxi Scooter',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 11.7,
    popularColors: ['Hitam Doff', 'Putih Mutiara', 'Abu-abu'],
    services: MATIC_SERVICES,
  },

  // YAMAHA MATIC
  {
    id: 'yamaha-nmax-turbo-2024-2026',
    brand: 'Yamaha',
    model: 'NMAX Turbo / Tech MAX (YECVT 2024-2026)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.1,
    popularColors: ['Magma Black', 'Elixir Dark Silver', 'Ceramic White', 'Dull Blue'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-nmax-155-connected',
    brand: 'Yamaha',
    model: 'NMAX 155 Connected / Standard',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.1,
    popularColors: ['Matte Black', 'Prestige Silver', 'Matte Blue', 'Metallic Red'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-aerox-155-alpha-2024-2026',
    brand: 'Yamaha',
    model: 'Aerox 155 Connected / CyberCity / SP',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['CyberCity Orange', 'Matte Black Gold', 'Silver Cyan', 'Racing Blue'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-fazzio-hybrid',
    brand: 'Yamaha',
    model: 'Fazzio Hybrid-Connected 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.1,
    popularColors: ['Neo Cyan', 'Neo Red', 'Lux White Pearl', 'Lux Prestige Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-grand-filano-hybrid',
    brand: 'Yamaha',
    model: 'Grand Filano Hybrid-Connected 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.4,
    popularColors: ['Lux White Pearl', 'Lux Dark Blue', 'Neo Dull Blue', 'Neo Pink Mauve'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-lexi-lx-155-2024-2026',
    brand: 'Yamaha',
    model: 'Lexi LX 155 (Standard / S / Connected-ABS)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Magma Black', 'Elixir Dark Silver', 'Matte Red', 'Metallic Black'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-xmax-connected-250',
    brand: 'Yamaha',
    model: 'XMAX Connected 250',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 13.0,
    popularColors: ['Dark Petrol', 'Premium Black', 'Prestige Grey'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-xride-125',
    brand: 'Yamaha',
    model: 'X-Ride 125 Crossover',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Sand Matte', 'Hitam Merah', 'Cyan Yellow', 'Putih'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-mio-m3',
    brand: 'Yamaha',
    model: 'Mio M3 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Cyan', 'Putih Kuning', 'Merah Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-gear-125',
    brand: 'Yamaha',
    model: 'Gear 125 Multiguna',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Navy', 'Matte Blue', 'Merah Grey', 'Cyan'],
    services: MATIC_SERVICES,
  },

  // SUZUKI MATIC
  {
    id: 'suzuki-burgman-street-125ex',
    brand: 'Suzuki',
    model: 'Burgman Street 125 EX',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.5,
    popularColors: ['Metallic Matte Black', 'Metallic Matte Platinum Silver', 'Metallic Royal Bronze'],
    services: MATIC_SERVICES,
  },
  {
    id: 'suzuki-avenis-125',
    brand: 'Suzuki',
    model: 'Avenis 125',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 5.2,
    popularColors: ['Pearl Mirage White', 'Metallic Matte Fibroin Grey'],
    services: MATIC_SERVICES,
  },
  {
    id: 'suzuki-nex-ii',
    brand: 'Suzuki',
    model: 'Nex II / Crossover 115',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.6,
    popularColors: ['Solid Black', 'Titan Black', 'Bordeaux Red'],
    services: MATIC_SERVICES,
  },

  // VESPA & PIAGGIO MATIC
  {
    id: 'vespa-sprint-150-i-get',
    brand: 'Vespa',
    model: 'Sprint 150 i-get ABS / Sprint S',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 7.0,
    popularColors: ['Green Tenace', 'Yellow Sole', 'White Innocenza', 'Black Vulcano'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-primavera-150-i-get',
    brand: 'Vespa',
    model: 'Primavera 150 i-get ABS / Primavera S',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 7.0,
    popularColors: ['Blue Capri', 'Beige Sabbia', 'Green Relax', 'White Innocenza'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-gts-super-150-300',
    brand: 'Vespa',
    model: 'GTS Super Sport 150 / 300 HPE',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 8.5,
    popularColors: ['Orange Tramonto', 'White Innocenza', 'Black Vulcano', 'Green Olive'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-lx-125-i-get',
    brand: 'Vespa',
    model: 'LX 125 i-get',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.0,
    popularColors: ['Red Passione', 'Grey Delicato', 'White Innocenza'],
    services: MATIC_SERVICES,
  },

  // BEBEK / UNDERBONE
  {
    id: 'honda-supra-x-125',
    brand: 'Honda',
    model: 'Supra X 125 FI (Helm-in / CW)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hitam Merah', 'Hitam Doff', 'Hitam Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-revo-x',
    brand: 'Honda',
    model: 'Revo X 110 FI',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Attractive Red', 'Quantum Black', 'Galaxy Blue'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-gtr-150',
    brand: 'Honda',
    model: 'Supra GTR 150 Sport Underbone',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.5,
    popularColors: ['Spartan Red', 'Gun Black', 'Exclusive Matte Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-super-cub-c125',
    brand: 'Honda',
    model: 'Super Cub C125 Classic',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 3.7,
    popularColors: ['Pearl Cadet Gray', 'Pearl Nebula Red', 'Matte Axis Gray'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-mx-king-150',
    brand: 'Yamaha',
    model: 'MX King 150',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.2,
    popularColors: ['Cyan Silver', 'Racing Blue', 'Red Black'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-jupiter-z1',
    brand: 'Yamaha',
    model: 'Jupiter Z1 115 FI',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.1,
    popularColors: ['Metallic Blue', 'Metallic Red', 'Metallic Black'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-satria-f150',
    brand: 'Suzuki',
    model: 'Satria F150 FI Hyper Underbone',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.0,
    popularColors: ['Titan Black', 'Pearl Bright Ivory', 'Solarize Silver'],
    services: BEBEK_SERVICES,
  },

  // SPORT & NAKED
  {
    id: 'honda-cbr150r',
    brand: 'Honda',
    model: 'CBR150R (Non-ABS / ABS)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Racing Red', 'Matte Black', 'Tricolor', 'MotoGP Edition'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-cbr250rr',
    brand: 'Honda',
    model: 'CBR250RR SP Quick Shifter',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.5,
    popularColors: ['Bravery Red Black', 'Mystic Blue', 'Honda Tricolor', 'Black Freedom'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-cb150r-streetfire',
    brand: 'Honda',
    model: 'CB150R Streetfire Naked',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Macho Matte Black', 'Fury Matte Red', 'Armored Matte Gray'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-r15-connected',
    brand: 'Yamaha',
    model: 'YZF-R15 V4 / R15M Connected-ABS',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 11.0,
    popularColors: ['Icon Blue', 'Tech Black', 'Silver M-Sport', 'World GP 60th'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-r25',
    brand: 'Yamaha',
    model: 'YZF-R25 Twin Cylinder',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.0,
    popularColors: ['Racing Blue', 'Metallic Black'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-xsr-155',
    brand: 'Yamaha',
    model: 'XSR 155 Heritage Sport',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 10.4,
    popularColors: ['Matte Black Elegance', 'Metallic Red Authentic', 'Light Blue Wanderlust'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-mt-15',
    brand: 'Yamaha',
    model: 'MT-15 Master of Torque',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 10.4,
    popularColors: ['Metallic Dark Grey (Cyan)', 'Metallic Blue', 'Matte Dark Grey'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-ninja-zx25r',
    brand: 'Kawasaki',
    model: 'Ninja ZX-25R / ZX-25RR (4 Silinder)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 15.0,
    popularColors: ['Lime Green / Ebony', 'Metallic Matte Graphenesteel Gray', 'Candy Persimmon Red'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-ninja-250',
    brand: 'Kawasaki',
    model: 'Ninja 250 FI (Twin Cylinder)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 14.0,
    popularColors: ['Lime Green', 'Metallic Carbon Gray', 'Passion Red'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-w175',
    brand: 'Kawasaki',
    model: 'W175 SE / Cafe / TR Retro',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 14.0,
    popularColors: ['Ebony Black', 'Metallic Ocean Blue', 'White'],
    services: SPORT_SERVICES,
  },
  {
    id: 'ktm-duke-250-390',
    brand: 'KTM',
    model: 'Duke 250 / 390 Naked',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 13.4,
    popularColors: ['Electronic Orange', 'Atlantic Blue', 'Silver Metallic'],
    services: SPORT_SERVICES,
  },

  // TRAIL / DUAL PURPOSE
  {
    id: 'honda-crf150l',
    brand: 'Honda',
    model: 'CRF150L Dual Purpose',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.2,
    popularColors: ['Extreme Red', 'Extreme Black', 'Extreme White', 'Extreme Green'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'yamaha-wr155r',
    brand: 'Yamaha',
    model: 'WR 155 R VVA',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.1,
    popularColors: ['Yamaha Blue', 'Yamaha Black', 'Monster Energy'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'kawasaki-klx-150',
    brand: 'Kawasaki',
    model: 'KLX 150 S / SE / SM (Supermoto)',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 6.9,
    popularColors: ['Lime Green', 'Ebony', 'Neon Green', 'Vivid Orange'],
    services: TRAIL_SERVICES,
  },

  // MOTOR LISTRIK (EV)
  {
    id: 'polytron-fox-r',
    brand: 'Polytron',
    model: 'Fox-R (3.74 kWh)',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Crimson Red', 'Cherry Red', 'Bumblebee Yellow', 'Midnight Black', 'White Pearl'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'alva-cervo',
    brand: 'Alva',
    model: 'Alva Cervo Boost / Cervo Q',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Mars Cooper', 'Supernova Black', 'Nebula Green', 'Halo White'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'honda-em1-e',
    brand: 'Honda',
    model: 'EM1 e: / EM1 e: PLUS',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Innovative White', 'Intelligent Matte Black', 'Smart Red'],
    services: EV_MOTOR_SERVICES,
  },

  // ==================== MOBIL ====================
  // TOYOTA
  {
    id: 'toyota-avanza-2024-2026',
    brand: 'Toyota',
    model: 'Avanza 1.3 / 1.5 G CVT (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Putih Mutiara', 'Hitam Metalik', 'Silver Mika', 'Abu-abu Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-veloz-2024-2026',
    brand: 'Toyota',
    model: 'Veloz 1.5 Q CVT TSS (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 43,
    popularColors: ['Platinum White Pearl', 'Black Metallic', 'Silver Mica Metallic', 'Dark Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-innova-zenix-gasoline',
    brand: 'Toyota',
    model: 'Kijang Innova Zenix 2.0 V / G Bensin',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 52,
    popularColors: ['Platinum White Pearl', 'Attitude Black', 'Silver Metallic', 'Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-innova-zenix-hybrid',
    brand: 'Toyota',
    model: 'Kijang Innova Zenix Hybrid 2.0 Q Modellista',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 52,
    popularColors: ['Platinum White Pearl', 'Attitude Black', 'Dark Steel', 'Silver Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-fortuner-gr-sport-diesel',
    brand: 'Toyota',
    model: 'Fortuner 2.8 VRZ / GR Sport Diesel 4x2',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 80,
    popularColors: ['Super White', 'Attitude Black', 'Silver Metallic', 'Dark Gray'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'toyota-raize-turbo',
    brand: 'Toyota',
    model: 'Raize 1.0 Turbo GR Sport CVT TSS',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 36,
    popularColors: ['Turquoise MM Black (Two Tone)', 'White Black', 'Yellow Black', 'Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-rush-gr-sport',
    brand: 'Toyota',
    model: 'Rush 1.5 S GR Sport',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['White', 'Black Mica', 'Silver Mica', 'Bronze Mica Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-calya',
    brand: 'Toyota',
    model: 'Calya 1.2 G',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['Putih', 'Hitam', 'Silver', 'Abu-abu Metalik', 'Merah'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-agya-gr-sport',
    brand: 'Toyota',
    model: 'Agya 1.2 G / GR Sport',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['White', 'Black', 'Red', 'Yellow', 'Silver'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-yaris-cross-hybrid',
    brand: 'Toyota',
    model: 'Yaris Cross 1.5 S Hybrid GR Sport TSS',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 36,
    popularColors: ['Platinum White Pearl Black', 'Scarlet Black', 'Dark Red Black', 'Silver Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HONDA MOBIL
  {
    id: 'honda-brio-satya-rs-2024-2026',
    brand: 'Honda',
    model: 'Brio Satya E / RS CVT (2024-2026)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 35,
    popularColors: ['Electric Lime Metallic', 'Crystal Black Pearl', 'Taffeta White', 'Rallye Red', 'Phoenix Orange Pearl Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-hrv-se-turbo',
    brand: 'Honda',
    model: 'HR-V 1.5 SE / RS Turbo',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Sand Khaki Pearl Two Tone', 'Ignite Red Metallic Two Tone', 'Platinum White Pearl', 'Meteoroid Gray'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-crv-turbo-ehev-2024-2026',
    brand: 'Honda',
    model: 'CR-V 1.5 Turbo / 2.0 RS e:HEV Hybrid (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 53,
    popularColors: ['Canyon River Blue Metallic', 'Platinum White Pearl', 'Crystal Black Pearl', 'Ignite Red Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-brv-n7x-edition',
    brand: 'Honda',
    model: 'BR-V Prestige with Honda SENSING / N7X Edition',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Sand Khaki Pearl', 'Premium Opal White Pearl', 'Crystal Black Pearl', 'Meteoroid Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-wrv-rs',
    brand: 'Honda',
    model: 'WR-V 1.5 RS with Honda SENSING',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 35,
    popularColors: ['Ignite Red Metallic Two Tone', 'Stellar Diamond Pearl', 'Meteoroid Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-city-hatchback-rs',
    brand: 'Honda',
    model: 'City Hatchback RS CVT Honda SENSING',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Phoenix Orange Pearl', 'Platinum White Pearl', 'Rallye Red', 'Meteoroid Gray'],
    services: CAR_GASOLINE_SERVICES,
  },

  // MITSUBISHI
  {
    id: 'mitsubishi-xpander-cross-2024-2026',
    brand: 'Mitsubishi',
    model: 'Xpander Ultimate / Xpander Cross CVT (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 45,
    popularColors: ['Quartz White Pearl', 'Blade Silver Metallic', 'Jet Black Mica', 'Green Bronze Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mitsubishi-pajero-sport-dakar-2024-2026',
    brand: 'Mitsubishi',
    model: 'Pajero Sport Dakar Ultimate 4x2 / 4x4 (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 68,
    popularColors: ['White Diamond', 'Black Mica', 'Blade Silver Metallic', 'Deep Bronze'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'mitsubishi-xforce',
    brand: 'Mitsubishi',
    model: 'Xforce Ultimate / Exceed CVT (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Energetic Yellow Metallic', 'Quartz White Pearl', 'Jet Black Mica', 'Red Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },

  // SUZUKI MOBIL
  {
    id: 'suzuki-xl7-hybrid',
    brand: 'Suzuki',
    model: 'XL7 Smart Hybrid Alpha / Beta',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Savanna Ivory Black Two Tone', 'Rising Orange Black', 'White Pearl', 'Metallic Magma Gray'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-ertiga-hybrid',
    brand: 'Suzuki',
    model: 'All New Ertiga Cruise / Hybrid GX',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Cool Black', 'Pearl Snow White', 'Metallic Magma Gray', 'Prime Cool Black Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-jimny-3-5-door',
    brand: 'Suzuki',
    model: 'Jimny 3-Door / 5-Door 4x4 (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Kinetic Yellow Black', 'Jungle Green', 'Chiffon Ivory', 'Granite Gray'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HYUNDAI
  {
    id: 'hyundai-stargazer-x',
    brand: 'Hyundai',
    model: 'Stargazer X Prime / Trend',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 40,
    popularColors: ['Optic White Matte', 'Titan Gray Matte', 'Creamy White Pearl', 'Midnight Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'hyundai-creta-prime',
    brand: 'Hyundai',
    model: 'Creta Prime / Alpha 1.5 IVT',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Magnetic Silver Matte', 'Dragon Red Pearl', 'Galaxy Blue Pearl', 'Midnight Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'hyundai-ioniq-5-ev',
    brand: 'Hyundai',
    model: 'Ioniq 5 Signature Long Range EV',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Gravity Gold Matte', 'Optic White', 'Midnight Black Pearl', 'Titan Gray Metallic'],
    services: CAR_EV_SERVICES,
  },

  // WULING
  {
    id: 'wuling-air-ev-long-range',
    brand: 'Wuling',
    model: 'Air EV Long Range / Standard Range',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Pristine White', 'Avocado Green', 'Lemon Yellow', 'Peach Pink', 'Galaxy Blue'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-binguo-ev',
    brand: 'Wuling',
    model: 'Binguo EV Premium / Long Range (333 - 410 KM)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Milk Tea', 'Mousse Green', 'Galaxy Blue'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-cloud-ev-2024-2026',
    brand: 'Wuling',
    model: 'Cloud EV 460 KM (2024-2026)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Milk Tea', 'Breeze White', 'Starry Black'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'wuling-alvez',
    brand: 'Wuling',
    model: 'Alvez EX / CE 1.5 CVT',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Tungsten Steel Gray', 'Pristine White', 'Starry Black', 'Aurora Silver', 'Carnelian Red'],
    services: CAR_GASOLINE_SERVICES,
  },

  // ==================== TAMBAHAN MOTOR POPULER & LEGENDARIS ====================
  // HONDA MOTOR
  {
    id: 'honda-vario-150-esp',
    brand: 'Honda',
    model: 'Vario 150 eSP (2015-2022)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.5,
    popularColors: ['Exclusive Matte Black', 'Exclusive Matte Silver', 'Matte Brown', 'Pearl White'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-beat-fi-esp-old',
    brand: 'Honda',
    model: 'BeAT eSP / Karbu (2008-2023)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hard Rock Black', 'Dance White', 'Electro Blue', 'Garage Black'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-pcx-150',
    brand: 'Honda',
    model: 'PCX 150 Lokal (2018-2021)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.0,
    popularColors: ['Wonderful White', 'Brilliant Black', 'Majestic Matte Red', 'Magnificent Matte Brown'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-adv-150',
    brand: 'Honda',
    model: 'ADV 150 (CBS / ABS 2019-2022)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 8.0,
    popularColors: ['Tough Matte Brown', 'Tough Matte Black', 'Tough Red', 'Tough Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'honda-sonic-150r',
    brand: 'Honda',
    model: 'Sonic 150R Underbone',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 4.0,
    popularColors: ['Activo Black', 'Energetic Red', 'Honda Racing Red'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-cb150-verza',
    brand: 'Honda',
    model: 'CB150 Verza 150',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 12.2,
    popularColors: ['Macho Matte Black', 'Bold Red', 'Masculine Black'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-tiger-revo',
    brand: 'Honda',
    model: 'Tiger Revo 200 (Legendaris)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 13.0,
    popularColors: ['Hitam Asimetris', 'Merah Marun', 'Abu-abu Metalik'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-megapro-fi',
    brand: 'Honda',
    model: 'MegaPro 150 FI / Primus',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 12.0,
    popularColors: ['Hitam', 'Merah Metalik', 'Biru'],
    services: SPORT_SERVICES,
  },

  // YAMAHA MOTOR
  {
    id: 'yamaha-nmax-155-old',
    brand: 'Yamaha',
    model: 'NMAX 155 Old Generasi 1 (2015-2019)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 6.6,
    popularColors: ['Matte Black Gold Velg', 'Matte Grey', 'White Pearl', 'Glossy Blue'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-vixion-nvl-advance-r',
    brand: 'Yamaha',
    model: 'Vixion (NVL / Advance NVA / Vixion R 155)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Matte Blue', 'Matte Grey', 'Metallic Black', 'Lover Red'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-rx-king-135',
    brand: 'Yamaha',
    model: 'RX-King 135 (Raja Jalanan Legendaris 2-Tak)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 9.5,
    popularColors: ['Hitam Emas (Gold Edition)', 'Biru Metalik', 'Merah Cabe', 'Hijau Botol'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-scorpio-z-225',
    brand: 'Yamaha',
    model: 'Scorpio Z 225 Steko / New',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 12.0,
    popularColors: ['Hitam Polos', 'Merah Silver', 'Putih Biru'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-jupiter-mx-135',
    brand: 'Yamaha',
    model: 'Jupiter MX 135 (Old / New 5-Speed)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hitam Biru', 'Merah Putih', 'Hijau'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-fino-125',
    brand: 'Yamaha',
    model: 'Fino 125 Blue Core (Grande / Premium)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Matte Red', 'White Caramel', 'Black Espresso'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-mio-sporty-smile',
    brand: 'Yamaha',
    model: 'Mio Sporty / Mio Smile Karbu (2003-2012)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.7,
    popularColors: ['Kuning', 'Putih', 'Hitam', 'Biru Telur Asin', 'Merah'],
    services: MATIC_SERVICES,
  },

  // SUZUKI MOTOR
  {
    id: 'suzuki-satria-fu-150-karbu',
    brand: 'Suzuki',
    model: 'Satria F150 DOHC Karbu Barong / Facelift',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Hitam Abu', 'Biru Putih Suzuki Racing', 'Merah Hitam'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-v-strom-250sx',
    brand: 'Suzuki',
    model: 'V-Strom 250SX Adventure',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 12.0,
    popularColors: ['Champion Yellow', 'Pearl Blaze Orange', 'Glass Sparkle Black'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'suzuki-thunder-125',
    brand: 'Suzuki',
    model: 'Thunder 125',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 15.0,
    popularColors: ['Hitam Metalik', 'Biru', 'Merah'],
    services: SPORT_SERVICES,
  },

  // KAWASAKI MOTOR
  {
    id: 'kawasaki-ninja-150-rr',
    brand: 'Kawasaki',
    model: 'Ninja 150 RR / 150 R Super KIPS (2-Tak)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 10.8,
    popularColors: ['Lime Green', 'Ebony Black', 'Candy Lime Green', 'Pearl White SE'],
    services: SPORT_SERVICES,
  },
  {
    id: 'kawasaki-klx-230',
    brand: 'Kawasaki',
    model: 'KLX 230 / KLX 230 SM Supermoto',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 7.5,
    popularColors: ['Lime Green', 'Battle Gray', 'Ebony'],
    services: TRAIL_SERVICES,
  },
  {
    id: 'kawasaki-d-tracker-150',
    brand: 'Kawasaki',
    model: 'D-Tracker 150 Supermoto SE',
    type: 'motor',
    category: 'Trail',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 6.9,
    popularColors: ['Neon Green', 'Shiny Yellow', 'Ebony Gold Velg'],
    services: TRAIL_SERVICES,
  },

  // MOTOR LISTRIK LAINNYA
  {
    id: 'gesits-raya-g',
    brand: 'Gesits',
    model: 'Gesits Raya G / G1 Electric',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Merah Berani', 'Putih Mutiara', 'Hitam Doff'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'smoot-zuzu-ev',
    brand: 'Smoot',
    model: 'Smoot Zuzu Retro EV (Swap Baterai)',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Vanilla Cream', 'Boba Black', 'Matcha Green', 'Bubble Gum Blue'],
    services: EV_MOTOR_SERVICES,
  },
  {
    id: 'united-tx3000-ev',
    brand: 'United',
    model: 'United TX3000 / T1800 Maxi EV',
    type: 'motor',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Matte Black', 'London Grey', 'Milano Red'],
    services: EV_MOTOR_SERVICES,
  },

  // ==================== TAMBAHAN MOBIL POPULER ====================
  // TOYOTA MOBIL
  {
    id: 'toyota-innova-reborn-diesel',
    brand: 'Toyota',
    model: 'Kijang Innova Reborn 2.4 G/V Diesel 2GD',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'dexlite',
    tankCapacityLiters: 55,
    popularColors: ['Super White', 'Attitude Black Mica', 'Silver Metallic', 'Dark Grey Mica'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'toyota-innova-reborn-gasoline',
    brand: 'Toyota',
    model: 'Kijang Innova Reborn 2.0 G/V Bensin 1TR',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 55,
    popularColors: ['Super White', 'Attitude Black Mica', 'Silver Metallic', 'Phantom Brown'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-yaris-lele-joker',
    brand: 'Toyota',
    model: 'Yaris 1.5 GR Sport / TRD Sportivo (Bakpao/Lele/Joker)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Citrus Mica Metallic', 'Super White', 'Attitude Black Mica', 'Red Mica Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-vios-gen3-4',
    brand: 'Toyota',
    model: 'Vios 1.5 G CVT TSS Sedan',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Platinum White Pearl', 'Metal Stream Metallic', 'Attitude Black', 'Red Mica'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-alphard-vellfire-hybrid',
    brand: 'Toyota',
    model: 'Alphard / Vellfire 2.5 HEV Hybrid (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 60,
    popularColors: ['Platinum White Pearl Luxury', 'Black Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-hilux-gr-sport',
    brand: 'Toyota',
    model: 'Hilux Double Cabin 2.8 GR Sport 4x4 Diesel',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 80,
    popularColors: ['Super White II', 'Attitude Black Mica', 'Emotional Red'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'toyota-sienta',
    brand: 'Toyota',
    model: 'Sienta 1.5 Q / V Sliding Door',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 42,
    popularColors: ['Orange Metallic', 'Super White II', 'Silver Mica Metallic', 'Attitude Black'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HONDA MOBIL
  {
    id: 'honda-jazz-ge8-gk5',
    brand: 'Honda',
    model: 'Jazz 1.5 RS (GD3 / GE8 / GK5 Legendaris)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 40,
    popularColors: ['Phoenix Orange Pearl', 'Taffeta White', 'Crystal Black Pearl', 'Rallye Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-civic-turbo-rs',
    brand: 'Honda',
    model: 'Civic 1.5 RS Turbo (FC / FE 2024-2026)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 47,
    popularColors: ['Ignite Red Metallic', 'Meteoroid Gray Metallic', 'Platinum White Pearl', 'Crystal Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-mobilio-rs',
    brand: 'Honda',
    model: 'Mobilio 1.5 E / RS CVT',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 42,
    popularColors: ['Phoenix Orange Pearl Two Tone', 'White Orchid Pearl', 'Crystal Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-freed-psd',
    brand: 'Honda',
    model: 'Freed 1.5 E PSD Sliding Door',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 42,
    popularColors: ['Brilliant White Pearl', 'Polished Metal Metallic', 'Crystal Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },

  // DAIHATSU MOBIL
  {
    id: 'daihatsu-xenia-all-gen',
    brand: 'Daihatsu',
    model: 'Xenia 1.3 / 1.5 R ADS CVT (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Greenish Gun Metal', 'Purplish Silver', 'Icy White', 'Classic Silver'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-sigra-facelift',
    brand: 'Daihatsu',
    model: 'Sigra 1.0 / 1.2 R Deluxe',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['Scarlet Red Metallic', 'Icy White Solid', 'Ultra Black Solid', 'Dark Grey Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-terios-custom',
    brand: 'Daihatsu',
    model: 'Terios 1.5 R Custom / ADS (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Silver Metallic', 'Bronze Metallic', 'Icy White', 'Midnight Black Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-ayla-ads',
    brand: 'Daihatsu',
    model: 'Ayla 1.0 / 1.2 R ADS CVT (2024-2026)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 36,
    popularColors: ['Ruby Red Metallic', 'Metallic Orange', 'Icy White', 'Ultra Black'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-gran-max-pickup-blindvan',
    brand: 'Daihatsu',
    model: 'Gran Max Pick Up / Blind Van / Minibus 1.3/1.5',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Ultra Black Solid', 'Icy White Solid', 'Classic Silver Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },

  // SUZUKI MOBIL
  {
    id: 'suzuki-swift-sport-gx',
    brand: 'Suzuki',
    model: 'Swift 1.4 / 1.5 GX / Swift Sport',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 42,
    popularColors: ['Champion Yellow', 'Speedy Blue Metallic', 'Pure White Pearl', 'Super Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-baleno-hatchback',
    brand: 'Suzuki',
    model: 'Baleno Hatchback 1.5 AT (2024-2026)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 37,
    popularColors: ['Celestial Blue', 'Pearl Midnight Black', 'Prime Grandeur Grey', 'Pearl Arctic White'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-ignis-gx',
    brand: 'Suzuki',
    model: 'Ignis 1.2 GX Urban SUV',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 32,
    popularColors: ['Lucent Orange Black', 'Stargaze Blue Black', 'Silky Silver'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-carry-pickup',
    brand: 'Suzuki',
    model: 'New Carry Pick Up Wide Deck / Flat Deck',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Real Black', 'White', 'Silky Silver'],
    services: CAR_GASOLINE_SERVICES,
  },

  // NISSAN MOBIL
  {
    id: 'nissan-serena-c28-epower-2024-2026',
    brand: 'Nissan',
    model: 'Serena e-POWER C28 Highway Star (2024-2026)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 52,
    popularColors: ['Turquoise Two Tone', 'Prism White', 'Diamond Black', 'Cardinal Red'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'nissan-grand-livina-all',
    brand: 'Nissan',
    model: 'Grand Livina 1.5 XV / All New Livina VE/VL',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 52,
    popularColors: ['Timeless Black', 'White Pearl', 'Ruby Red', 'Silver Tech'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'nissan-xtrail-t31-t32',
    brand: 'Nissan',
    model: 'X-Trail 2.0 / 2.5 CVT (T31 / T32)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 60,
    popularColors: ['Monarch Orange', 'Diamond Black', 'Storm White', 'Brilliant Silver'],
    services: CAR_GASOLINE_SERVICES,
  },

  // MAZDA MOBIL
  {
    id: 'mazda-cx5-kuro-elite',
    brand: 'Mazda',
    model: 'CX-5 2.5 Elite / Kuro Edition AWD',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 56,
    popularColors: ['Soul Red Crystal Metallic', 'Machine Grey Metallic', 'Rhodium White', 'Polymetal Grey Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mazda-cx3-sport-pro',
    brand: 'Mazda',
    model: 'CX-3 1.5 Sport / 2.0 Pro',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 48,
    popularColors: ['Soul Red Crystal', 'Aero Grey Metallic', 'Platinum Quartz Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mazda-3-hatchback-sedan',
    brand: 'Mazda',
    model: 'Mazda 3 Hatchback / Sedan SkyActiv-G',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 51,
    popularColors: ['Soul Red Crystal', 'Polymetal Grey', 'Jet Black Mica'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HYUNDAI MOBIL
  {
    id: 'hyundai-santa-fe-2024-2026',
    brand: 'Hyundai',
    model: 'All New Santa Fe 1.6 Turbo Hybrid / 2.5 Gasoline (2024-2026)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 67,
    popularColors: ['Terracotta Orange', 'Creamy White Pearl', 'Abyss Black Pearl', 'Magnetic Gray Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'hyundai-palisade-signature',
    brand: 'Hyundai',
    model: 'Palisade 2.2 D Signature AWD Diesel',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamina_dex',
    tankCapacityLiters: 71,
    popularColors: ['Moonlight Blue Pearl', 'Abyss Black Pearl', 'Creamy White Pearl', 'Shimmering Silver Metallic'],
    services: CAR_DIESEL_SERVICES,
  },

  // CHERY MOBIL
  {
    id: 'chery-omoda-5-gt',
    brand: 'Chery',
    model: 'Omoda 5 R / Z / GT AWD 1.6 Turbo',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 51,
    popularColors: ['Grey Morganite', 'White Howlite Black Two Tone', 'Black Platinum'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'chery-omoda-e5-ev',
    brand: 'Chery',
    model: 'Omoda E5 Pure EV (430 KM)',
    type: 'mobil',
    category: 'Listrik',
    defaultFuel: 'listrik',
    tankCapacityLiters: 0,
    popularColors: ['Greenish Mint', 'White Howlite Two Tone', 'Titanium Grey'],
    services: CAR_EV_SERVICES,
  },
  {
    id: 'chery-tiggo-8-pro-max',
    brand: 'Chery',
    model: 'Tiggo 8 Pro / Max 2.0 TGDI 7-Seater',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 57,
    popularColors: ['Rhine Blue', 'White Howlite', 'Black Platinum', 'Tekno Grey'],
    services: CAR_GASOLINE_SERVICES,
  },

  // BMW MOBIL
  {
    id: 'bmw-seri-3-320i-330i',
    brand: 'BMW',
    model: 'BMW 320i / 330i M Sport (F30 / G20 LCI)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 59,
    popularColors: ['Portimao Blue Metallic', 'Alpine White', 'Black Sapphire', 'Brooklyn Grey Metallic'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'bmw-x3-xdrive',
    brand: 'BMW',
    model: 'BMW X3 xDrive30i M Sport',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 65,
    popularColors: ['Phytonic Blue', 'Mineral White', 'Carbon Black'],
    services: CAR_GASOLINE_SERVICES,
  },

  // MERCEDES-BENZ MOBIL
  {
    id: 'mercedes-benz-c-class-c200-c300',
    brand: 'Mercedes-Benz',
    model: 'C-Class C 200 / C 300 AMG Line (W205 / W206)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 66,
    popularColors: ['Polar White', 'Obsidian Black', 'Selenite Grey Metallic', 'Spectral Blue'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mercedes-benz-glc-amg',
    brand: 'Mercedes-Benz',
    model: 'GLC 300 4MATIC AMG Line SUV',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 62,
    popularColors: ['Polar White', 'Mojave Silver', 'Nautic Blue', 'Obsidian Black'],
    services: CAR_GASOLINE_SERVICES,
  },
  // ==================== KENDARAAN KLASIK / LAWAS (90s - 2000s) ====================
  // HONDA MOTOR LAWAS
  {
    id: 'honda-astrea-grand-bulus',
    brand: 'Honda',
    model: 'Astrea Grand / Bulus / Sabit (1991-1997)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hitam Striping Merah', 'Hitam Striping Hijau', 'Abu-abu'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-astrea-prima-star',
    brand: 'Honda',
    model: 'Astrea Prima / Star / Legenda (1985-2003)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.7,
    popularColors: ['Hitam Putih', 'Hitam Striping Emas', 'Merah'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-supra-x-100-fit',
    brand: 'Honda',
    model: 'Supra X 100 / Supra Fit / V (1997-2008)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.0,
    popularColors: ['Hitam Teromol', 'Hitam Cakram Double', 'Biru Silver', 'Merah Hitam'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-karisma-125',
    brand: 'Honda',
    model: 'Karisma 125 D / 125 X (2002-2005)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.7,
    popularColors: ['Biru Silver', 'Hitam Silver', 'Merah Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-gl-pro-neotech',
    brand: 'Honda',
    model: 'GL Pro Neotech / Black Engine / GL Max (1985-1999)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 10.0,
    popularColors: ['Hitam Striping Ungu Kuning', 'Hitam Striping Merah Biru'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-cb100-gelatik',
    brand: 'Honda',
    model: 'CB 100 / CB 125 Gelatik Klasik (1970-1982)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 8.5,
    popularColors: ['Putih Merah Gelatik', 'Hitam Putih', 'Biru Putih'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-win-100',
    brand: 'Honda',
    model: 'Win 100 (Semi Trail / Dinas 1984-2005)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 8.5,
    popularColors: ['Cokelat Dinas', 'Hitam', 'Biru'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-c70-pitung',
    brand: 'Honda',
    model: 'C70 Pitung / Kuntul / Bekjul Klasik (1971-1982)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.5,
    popularColors: ['Merah Marun Klasik', 'Hijau Tosca', 'Biru Muda', 'Krem'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'honda-tiger-2000-tilam',
    brand: 'Honda',
    model: 'Tiger 2000 Tilam / Lawas (1993-2006)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 13.0,
    popularColors: ['Ungu Terong', 'Hitam Striping Merah', 'Silver Metalik'],
    services: SPORT_SERVICES,
  },
  {
    id: 'honda-vario-110-karbu-agnes',
    brand: 'Honda',
    model: 'Vario 110 Karbu Agnes / Techno (2006-2013)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 3.6,
    popularColors: ['Merah Hitam', 'Putih Biru', 'Hitam Silver'],
    services: MATIC_SERVICES,
  },

  // YAMAHA MOTOR LAWAS
  {
    id: 'yamaha-f1zr-caltex-marlboro',
    brand: 'Yamaha',
    model: 'F1ZR / F1Z / Force 1 110 (2-Tak 1992-2004)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Caltex Edition Hijau Merah', 'Marlboro Merah Putih', 'Millenium Orange Silver', 'Biru Putih'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-jupiter-z-burhan',
    brand: 'Yamaha',
    model: 'Jupiter Z Burhan / Burung Hantu (2006-2009)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Merah Hitam', 'Biru Silver', 'Hijau Hitam', 'Hitam Polos'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-vega-r-lama',
    brand: 'Yamaha',
    model: 'Vega R / Vega Lama (1999-2008)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.2,
    popularColors: ['Biru Silver', 'Hitam Orange', 'Merah Hitam'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-nouvo-lele-z',
    brand: 'Yamaha',
    model: 'Nouvo Lele (2002-2004) / Nouvo Z (2005-2007)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.8,
    popularColors: ['Emas Champagne', 'Hitam', 'Biru Metalik', 'Silver'],
    services: MATIC_SERVICES,
  },
  {
    id: 'yamaha-rx-king-cobra-master',
    brand: 'Yamaha',
    model: 'RX-King Cobra (1983-1995) / Master (1996-2001)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 9.5,
    popularColors: ['Hitam Cobra', 'Merah Cabe', 'Biru Laut'],
    services: SPORT_SERVICES,
  },
  {
    id: 'yamaha-alfa-champ-2tak',
    brand: 'Yamaha',
    model: 'Alfa II R / Champ 102cc (2-Tak 1988-1996)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Merah Putih', 'Hitam Striping Emas', 'Biru'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'yamaha-vixion-old-lampu-bulat',
    brand: 'Yamaha',
    model: 'Vixion Old Lampu Bulat 3C1 (2007-2010)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 12.0,
    popularColors: ['Hitam Merah', 'Hitam Silver', 'Biru Putih'],
    services: SPORT_SERVICES,
  },

  // SUZUKI MOTOR LAWAS
  {
    id: 'suzuki-satria-hiu-lumba-2tak',
    brand: 'Suzuki',
    model: 'Satria 120 R LSCM Hiu / Lumba-Lumba (2-Tak 1997-2005)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 5.2,
    popularColors: ['Kuning Hitam Hiu (Movistar)', 'Merah Putih', 'Biru Putih', 'Orange Hitam'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-shogun-110-kebo',
    brand: 'Suzuki',
    model: 'Shogun 110 Kebo / New (1996-2003)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Hitam Striping Hijau Ungu', 'Ungu Terong', 'Biru Silver'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-rgr-150',
    brand: 'Suzuki',
    model: 'RG-R 150 Sprinter / Crystal (2-Tak 1991-1997)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 11.0,
    popularColors: ['Biru Putih Suzuki Racing', 'Hitam Merah'],
    services: SPORT_SERVICES,
  },
  {
    id: 'suzuki-tornado-gs-gx',
    brand: 'Suzuki',
    model: 'Tornado GS / GX 110 (2-Tak 1997-2004)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Biru Silver', 'Hitam Merah', 'Kuning Hitam'],
    services: BEBEK_SERVICES,
  },
  {
    id: 'suzuki-rc100-bravo-sprinter',
    brand: 'Suzuki',
    model: 'RC 100 Bravo / Sprinter / Crystal (1985-1995)',
    type: 'motor',
    category: 'Bebek',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 4.5,
    popularColors: ['Hitam', 'Merah Maroon'],
    services: BEBEK_SERVICES,
  },

  // KAWASAKI & VESPA LAWAS
  {
    id: 'kawasaki-ninja-150-r-kiss',
    brand: 'Kawasaki',
    model: 'Ninja 150 R Lampu Bulat / Kiss (2-Tak 1996-2015)',
    type: 'motor',
    category: 'Sport',
    defaultFuel: 'pertamax_turbo',
    tankCapacityLiters: 10.8,
    popularColors: ['Hijau Botol Klasik', 'Hitam Striping Hijau', 'Merah Ferari'],
    services: SPORT_SERVICES,
  },
  {
    id: 'vespa-px-150-exclusive-excel',
    brand: 'Vespa',
    model: 'Vespa PX 150 / Exclusive 2 / Excel 150 (2-Tak 1980-2006)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 8.0,
    popularColors: ['Biru Malam', 'Putih Klasik', 'Merah Marun', 'Abu-abu Metalik'],
    services: MATIC_SERVICES,
  },
  {
    id: 'vespa-super-sprint-klasik',
    brand: 'Vespa',
    model: 'Vespa Super 150 / Sprint Veloce Klasik (1965-1979)',
    type: 'motor',
    category: 'Matic',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 7.7,
    popularColors: ['Biru Telur Asin', 'Putih Gading', 'Hijau Tosca Klasik'],
    services: MATIC_SERVICES,
  },

  // ==================== MOBIL LAWAS / 90s - 2000s ====================
  // TOYOTA MOBIL LAWAS
  {
    id: 'toyota-kijang-super-grand-extra',
    brand: 'Toyota',
    model: 'Kijang Super / Grand Extra 5K/7K (1986-1996)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Hijau Lumut', 'Abu-abu Metalik', 'Biru Malam', 'Merah Hati'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-kijang-kapsul-lgx-diesel-gas',
    brand: 'Toyota',
    model: 'Kijang Kapsul LGX / SGX / Krista (Bensin 1.8 & Diesel 2L 1997-2004)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 55,
    popularColors: ['Silver Two Tone', 'Biru Two Tone', 'Cokelat Metalik', 'Hijau Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-great-corolla-greco',
    brand: 'Toyota',
    model: 'Great Corolla (Greco AE101 1.6 SEG 1992-1997)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 50,
    popularColors: ['Abu-abu Metalik', 'Putih Solid', 'Biru Malam', 'Hitam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-corolla-dx-ke70',
    brand: 'Toyota',
    model: 'Corolla DX (KE70 Retro Klasik 1980-1983)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Kuning Mustard', 'Putih Klasik', 'Merah Bata', 'Biru Langit'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-starlet-kotak-kapsul',
    brand: 'Toyota',
    model: 'Starlet Kotak (EP70) / Kapsul (EP81) 1.0 & 1.3 (1985-1998)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 40,
    popularColors: ['Merah Cabe', 'Putih Solid', 'Silver Metalik', 'Hitam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-land-cruiser-fj40-hardtop',
    brand: 'Toyota',
    model: 'Land Cruiser FJ40 Hardtop 4x4 (1960-1984 Legendaris)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 65,
    popularColors: ['Kuning Mustard Klasik', 'Hijau Tentara', 'Merah', 'Biru'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-soluna-15-gli',
    brand: 'Toyota',
    model: 'Soluna 1.5 GLi / XLi (2000-2003)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Silver Metalik', 'Biru Metalik', 'Hitam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'toyota-avanza-gen-1-old',
    brand: 'Toyota',
    model: 'Avanza Generasi 1 (1.3 E/G & 1.5 S 2003-2011)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Silver Metalik', 'Champagne Emas', 'Hitam Mica', 'Biru Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },

  // HONDA MOBIL LAWAS
  {
    id: 'honda-civic-genio-estilo',
    brand: 'Honda',
    model: 'Civic Genio (Sedan SR4) / Estilo (Hatchback SR3 1992-1995)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 45,
    popularColors: ['Merah Ferio', 'Putih Grand Prix', 'Kuning Spoon', 'Biru Malam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-grand-civic-nouva',
    brand: 'Honda',
    model: 'Grand Civic (Sedan EF) / Civic Nouva (Hatchback EF 1988-1991)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 45,
    popularColors: ['Putih Solid', 'Merah Marun', 'Abu-abu Metalik', 'Hitam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-civic-ferio-so4',
    brand: 'Honda',
    model: 'Civic Ferio 1.6 VTEC (SO4 1996-2000)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 45,
    popularColors: ['Silver Metalik', 'Hijau Botol Dark Green', 'Hitam Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-city-type-z',
    brand: 'Honda',
    model: 'City Type Z 1.5 VTEC / Persona (SX8 1999-2002)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 42,
    popularColors: ['Silver Metalik', 'Emas Champagne', 'Hitam Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-accord-maestro-cielo',
    brand: 'Honda',
    model: 'Accord Maestro (1990-1993) / Accord Cielo (1994-1998)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 60,
    popularColors: ['Hitam Metalik', 'Abu-abu Metalik', 'Putih Mutiara', 'Hijau Tua'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-crv-gen-1-gen-2-konde',
    brand: 'Honda',
    model: 'CR-V Gen 1 (RD1 1999-2001) / CR-V Gen 2 Konde (RD4 2002-2006)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 58,
    popularColors: ['Silver Stone', 'Hitam Nighthawk', 'Emas Sahara', 'Biru Tua'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'honda-stream-17-20',
    brand: 'Honda',
    model: 'Stream 1.7 / 2.0 i-VTEC (2002-2007)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 55,
    popularColors: ['Silver Metalik', 'Hitam Nighthawk', 'Cokelat Abu'],
    services: CAR_GASOLINE_SERVICES,
  },

  // ISUZU MOBIL (RAJANYA DIESEL)
  {
    id: 'isuzu-panther-kapsul-touring',
    brand: 'Isuzu',
    model: 'Panther Kapsul Touring / Grand Touring / LS / LV (2.5 Turbo 2000-2020)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'dexlite',
    tankCapacityLiters: 55,
    popularColors: ['Cokelat Two Tone', 'Hitam Solid', 'Silver Two Tone', 'Hijau Botol Two Tone'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'isuzu-panther-kotak-hi-grade',
    brand: 'Isuzu',
    model: 'Panther Kotak 2.3 / 2.5 Hi-Grade / Miyabi (1991-2000)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 50,
    popularColors: ['Hijau Metalik', 'Abu-abu Two Tone', 'Merah Marun Two Tone'],
    services: CAR_DIESEL_SERVICES,
  },

  // DAIHATSU MOBIL LAWAS
  {
    id: 'daihatsu-taft-gt-rocky-f70',
    brand: 'Daihatsu',
    model: 'Taft GT / Rocky / Hiline 4x4 Diesel (F70 / F73 1985-2002)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'dexlite',
    tankCapacityLiters: 60,
    popularColors: ['Hitam Doff', 'Putih Solid', 'Merah', 'Hijau Tentara'],
    services: CAR_DIESEL_SERVICES,
  },
  {
    id: 'daihatsu-feroza-16',
    brand: 'Daihatsu',
    model: 'Feroza 1.6 G2 / Megatop (1993-1999)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 50,
    popularColors: ['Merah Abu Two Tone', 'Biru Abu Two Tone', 'Hitam'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-taruna-csx-fgx-oxxy',
    brand: 'Daihatsu',
    model: 'Taruna CSX / FGX / Oxxy 1.5/1.6 (1999-2006)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 48,
    popularColors: ['Silver Two Tone', 'Biru Two Tone', 'Hitam Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'daihatsu-espass-zebra-sliding',
    brand: 'Daihatsu',
    model: 'Espass / Zebra 1.3 & 1.6 Pintu Geser (1990-2007)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 43,
    popularColors: ['Merah Metalik', 'Biru Malam', 'Silver', 'Hijau'],
    services: CAR_GASOLINE_SERVICES,
  },

  // SUZUKI MOBIL LAWAS
  {
    id: 'suzuki-katana-jimny-sj410',
    brand: 'Suzuki',
    model: 'Katana / Jimny Sierra / Caribian (SJ410 / SJ413 1984-2006)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 40,
    popularColors: ['Putih Solid', 'Hitam', 'Merah Ferari', 'Hijau Daun'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-karimun-kotak-classic',
    brand: 'Suzuki',
    model: 'Karimun Kotak 1.0 Classic (1999-2006)',
    type: 'mobil',
    category: 'Hatchback',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 35,
    popularColors: ['Silver Metalik', 'Biru Telur Asin', 'Merah Cabe', 'Kuning'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-escudo-vitara-sidekick',
    brand: 'Suzuki',
    model: 'Vitara 4x4 / Escudo / Sidekick Gen 1 (1992-2000)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 55,
    popularColors: ['Merah Two Tone', 'Hijau Botol Two Tone', 'Hitam Two Tone', 'Biru'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'suzuki-baleno-sedan-old',
    brand: 'Suzuki',
    model: 'Baleno Sedan 1.5 / 1.6 (1997-2002)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 50,
    popularColors: ['Silver Metalik', 'Hijau Metalik', 'Hitam', 'Biru'],
    services: CAR_GASOLINE_SERVICES,
  },

  // MITSUBISHI & NISSAN LAWAS
  {
    id: 'mitsubishi-kuda-grandia-diamond',
    brand: 'Mitsubishi',
    model: 'Kuda Grandia / Diamond (Bensin 1.6/2.0 & Diesel 2.5 1999-2005)',
    type: 'mobil',
    category: 'MPV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 55,
    popularColors: ['Silver Two Tone', 'Biru Two Tone', 'Hijau Two Tone', 'Hitam Two Tone'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mitsubishi-galant-hiu-v6',
    brand: 'Mitsubishi',
    model: 'Galant Hiu V6-24 DOHC 2.5 (1998-2005)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 64,
    popularColors: ['Hitam Metalik', 'Silver Metalik', 'Putih Mutiara'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mitsubishi-lancer-evo3-evo4-ck4',
    brand: 'Mitsubishi',
    model: 'Lancer GLXi / SEi / Evo 3 / Evo 4 (CB4 / CK4 1993-2002)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 50,
    popularColors: ['Kuning Evo', 'Putih Solid', 'Hitam Metalik', 'Merah'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'nissan-terrano-kingsroad',
    brand: 'Nissan',
    model: 'Terrano Kingsroad / Spirit / Grand Road (1995-2006)',
    type: 'mobil',
    category: 'SUV',
    defaultFuel: 'pertalite',
    tankCapacityLiters: 65,
    popularColors: ['Hitam Two Tone', 'Hijau Tua Two Tone', 'Silver Metalik'],
    services: CAR_GASOLINE_SERVICES,
  },

  // BMW & MERCY LAWAS
  {
    id: 'bmw-seri-3-e30-mas-boy',
    brand: 'BMW',
    model: 'BMW Seri 3 E30 318i M40 (Mas Boy 1986-1991)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 55,
    popularColors: ['Alpinweiss Putih', 'Diamantschwarz Hitam', 'Zinnoberrot Merah', 'Lachssilber Silver'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'bmw-seri-3-e36',
    brand: 'BMW',
    model: 'BMW Seri 3 E36 320i / 323i / 328i (1991-1998)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 62,
    popularColors: ['Boston Green', 'Mauritius Blue', 'Cosmosschwarz Hitam', 'Hellrot Merah'],
    services: CAR_GASOLINE_SERVICES,
  },
  {
    id: 'mercedes-benz-w124-boxer',
    brand: 'Mercedes-Benz',
    model: 'Mercedes-Benz W124 Boxer E220 / E320 / 300E (1985-1996)',
    type: 'mobil',
    category: 'Sedan',
    defaultFuel: 'pertamax',
    tankCapacityLiters: 70,
    popularColors: ['Smoke Silver', 'Midnight Blue', 'Brilliant Silver', 'Black Pearl'],
    services: CAR_GASOLINE_SERVICES,
  },
];

export const POPULAR_MOTOR_BRANDS = [
  'Semua',
  'Honda',
  'Yamaha',
  'Suzuki',
  'Kawasaki',
  'Vespa',
  'KTM',
  'Polytron',
  'Alva',
  'Gesits',
  'Smoot',
  'United',
];

export const POPULAR_CAR_BRANDS = [
  'Semua',
  'Toyota',
  'Honda',
  'Daihatsu',
  'Mitsubishi',
  'Suzuki',
  'Isuzu',
  'Nissan',
  'Hyundai',
  'Wuling',
  'BYD',
  'Chery',
  'Mazda',
  'BMW',
  'Mercedes-Benz',
];

export const MOTOR_CATEGORIES = ['Semua', 'Matic', 'Bebek', 'Sport', 'Trail', 'Listrik'];
export const CAR_CATEGORIES = ['Semua', 'MPV', 'SUV', 'Hatchback', 'Sedan', 'Listrik'];


