import { FuelLog, ServiceLog, Vehicle } from '../types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-motor-1',
    name: 'Honda Vario 160 CBS',
    brand: 'Honda',
    model: 'Vario 160',
    year: 2023,
    type: 'motor',
    plateNumber: 'B 3482 UMX',
    currentKm: 14250,
    fuelType: 'pertamax',
    tankCapacityLiters: 5.5,
    color: 'Matte Black',
    taxExpiryDate: '2026-10-18', // ~1 bulan lagi
    tax5YearExpiryDate: '2028-10-18',
    createdAt: '2025-01-10T08:00:00.000Z',
    maintenanceItems: [
      {
        id: 'maint-1',
        name: 'Oli Mesin (SPX 2 / MPX 2)',
        category: 'oil',
        lastReplacedKm: 12000,
        lastReplacedDate: '2026-07-15',
        intervalKm: 2500, // jatuh tempo di 14.500 km (sisa 250 km -> PERLU PERHATIAN!)
        intervalMonths: 3,
        notes: 'Gunakan oli standar Honda SPX 2 0.8L 10W-30',
      },
      {
        id: 'maint-2',
        name: 'Oli Gardan / Transmisi',
        category: 'transmission',
        lastReplacedKm: 8000,
        lastReplacedDate: '2026-03-10',
        intervalKm: 8000, // jatuh tempo di 16.000 km (sisa 1.750 km -> AMAN)
        intervalMonths: 6,
        notes: 'Ganti setiap 2-3 kali ganti oli mesin (120ml)',
      },
      {
        id: 'maint-3',
        name: 'Filter Udara',
        category: 'filter',
        lastReplacedKm: 10000,
        lastReplacedDate: '2026-05-20',
        intervalKm: 10000,
        intervalMonths: 12,
        notes: 'Tipe viscous element, ganti jika sudah kotor/hitam',
      },
      {
        id: 'maint-4',
        name: 'Busi Standar (NGK CPR9EA-9)',
        category: 'general',
        lastReplacedKm: 8000,
        lastReplacedDate: '2026-03-10',
        intervalKm: 8000,
        intervalMonths: 12,
        notes: 'Cek celah elektroda busi',
      },
      {
        id: 'maint-5',
        name: 'Kampas Rem Depan & Belakang',
        category: 'brakes',
        lastReplacedKm: 10000,
        lastReplacedDate: '2026-05-20',
        intervalKm: 10000,
        intervalMonths: 12,
        notes: 'Periksa ketebalan kampas cakram',
      },
      {
        id: 'maint-6',
        name: 'Pajak STNK Tahunan',
        category: 'tax',
        lastReplacedKm: 0,
        lastReplacedDate: '2025-10-18',
        intervalKm: 0,
        intervalMonths: 12,
        targetDate: '2026-10-18',
        notes: 'Bayar via aplikasi Signal atau Samsat Keliling',
      },
    ],
  },
  {
    id: 'veh-car-1',
    name: 'Toyota Avanza Veloz 1.5 Q',
    brand: 'Toyota',
    model: 'Veloz 1.5 Q CVT',
    year: 2022,
    type: 'mobil',
    plateNumber: 'B 1873 TRK',
    currentKm: 38400,
    fuelType: 'pertamax',
    tankCapacityLiters: 43,
    color: 'Platinum White Pearl',
    taxExpiryDate: '2026-12-05',
    tax5YearExpiryDate: '2027-12-05',
    createdAt: '2024-11-20T10:00:00.000Z',
    maintenanceItems: [
      {
        id: 'maint-car-1',
        name: 'Oli Mesin Full Synthetic (0W-20)',
        category: 'oil',
        lastReplacedKm: 30000,
        lastReplacedDate: '2026-04-12',
        intervalKm: 10000, // sisa 1.600 km
        intervalMonths: 6,
        notes: 'Toyota Motor Oil (TMO) Full Synthetic 0W-20 SN GF-5',
      },
      {
        id: 'maint-car-2',
        name: 'Filter Oli Mesin',
        category: 'filter',
        lastReplacedKm: 30000,
        lastReplacedDate: '2026-04-12',
        intervalKm: 10000,
        intervalMonths: 6,
        notes: 'Wajib diganti setiap pergantian oli mesin',
      },
      {
        id: 'maint-car-3',
        name: 'Rotasi Ban & Spooring Balancing',
        category: 'general',
        lastReplacedKm: 30000,
        lastReplacedDate: '2026-04-12',
        intervalKm: 10000,
        intervalMonths: 6,
        notes: 'Jaga keausan tapak ban merata',
      },
      {
        id: 'maint-car-4',
        name: 'Pajak STNK Tahunan',
        category: 'tax',
        lastReplacedKm: 0,
        lastReplacedDate: '2025-12-05',
        intervalKm: 0,
        intervalMonths: 12,
        targetDate: '2026-12-05',
        notes: 'Estimasi PKB sekitar Rp 3.850.000',
      },
    ],
  },
];

export const INITIAL_FUEL_LOGS: FuelLog[] = [
  {
    id: 'fuel-1',
    vehicleId: 'veh-motor-1',
    date: '2026-09-17T08:30:00.000Z',
    odometer: 14250,
    liters: 4.2,
    totalPrice: 54390,
    pricePerLiter: 12950,
    fuelType: 'pertamax',
    gasStationName: 'SPBU Pertamina 31.12702 Kuningan',
    isFullTank: true,
    efficiencyKmPerL: 45.2,
    costPerKm: 286,
    notes: 'Isi full sepulang kerja',
  },
  {
    id: 'fuel-2',
    vehicleId: 'veh-motor-1',
    date: '2026-09-10T17:15:00.000Z',
    odometer: 14060,
    liters: 4.1,
    totalPrice: 53095,
    pricePerLiter: 12950,
    fuelType: 'pertamax',
    gasStationName: 'SPBU Shell MT Haryono',
    isFullTank: true,
    efficiencyKmPerL: 43.9,
    costPerKm: 295,
    notes: 'Tarikan mesin enteng',
  },
  {
    id: 'fuel-3',
    vehicleId: 'veh-motor-1',
    date: '2026-09-02T07:45:00.000Z',
    odometer: 13880,
    liters: 4.0,
    totalPrice: 51800,
    pricePerLiter: 12950,
    fuelType: 'pertamax',
    gasStationName: 'SPBU Pertamina Pancoran',
    isFullTank: true,
    efficiencyKmPerL: 44.0,
    costPerKm: 294,
  },
  {
    id: 'fuel-car-1',
    vehicleId: 'veh-car-1',
    date: '2026-09-15T09:00:00.000Z',
    odometer: 38400,
    liters: 32.5,
    totalPrice: 420875,
    pricePerLiter: 12950,
    fuelType: 'pertamax',
    gasStationName: 'SPBU Pertamina Rest Area KM 57',
    isFullTank: true,
    efficiencyKmPerL: 13.5,
    costPerKm: 959,
    notes: 'Perjalanan luar kota ke Bandung via Cipularang',
  },
  {
    id: 'fuel-car-2',
    vehicleId: 'veh-car-1',
    date: '2026-08-30T14:20:00.000Z',
    odometer: 37960,
    liters: 35.0,
    totalPrice: 453250,
    pricePerLiter: 12950,
    fuelType: 'pertamax',
    gasStationName: 'SPBU Shell TB Simatupang',
    isFullTank: true,
    efficiencyKmPerL: 12.8,
    costPerKm: 1011,
    notes: 'Rute harian macet tol dalam kota',
  },
];

export const INITIAL_SERVICE_LOGS: ServiceLog[] = [
  {
    id: 'serv-1',
    vehicleId: 'veh-motor-1',
    date: '2026-07-15T10:30:00.000Z',
    odometer: 12000,
    workshopName: 'AHASS Surya Motor Tebet',
    category: 'routine',
    itemsReplaced: [
      'Ganti Oli Mesin AHM SPX 2 0.8L',
      'Pembersihan CVT & Roller',
      'Penyetelan Rem & Rantai',
    ],
    totalCost: 145000,
    notes: 'Kondisi v-belt masih tebal, roller aman.',
  },
  {
    id: 'serv-2',
    vehicleId: 'veh-motor-1',
    date: '2026-05-20T11:00:00.000Z',
    odometer: 10000,
    workshopName: 'AHASS Surya Motor Tebet',
    category: 'routine',
    itemsReplaced: [
      'Filter Udara Original',
      'Kampas Rem Depan Honda Genuine',
      'Oli Mesin MPX 2',
    ],
    totalCost: 185000,
    notes: 'Filter udara diganti karena sudah kotor.',
  },
  {
    id: 'serv-car-1',
    vehicleId: 'veh-car-1',
    date: '2026-04-12T09:30:00.000Z',
    odometer: 30000,
    workshopName: 'Auto2000 Cilandak',
    category: 'routine',
    itemsReplaced: [
      'Oli Mesin TMO Full Synthetic 0W-20 (4 Liter)',
      'Filter Oli & Gasket Plug',
      'Rotasi Ban, Spooring & Balancing',
      'Pembersihan Filter AC Kabin',
    ],
    totalCost: 890000,
    notes: 'Servis berkala 30.000 km, aki dan kampas rem kondisi 85%.',
  },
];
